name: Build Preview

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemblePreview

      - name: Download Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeanStream-Preview-${{ github.sha }}
          path: app/build/outputs/apk/preview/app-preview.apk

