name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: adopt
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemblePreview
      - name: List
        run: tree

      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          path: app/build/outputs/apk/preview/app-preview.apk
          if-no-files-found: error
          
